# 搞定Python基本操作（科学计算）

学习资料为<http://www.jianshu.com/p/e17b397cff3c>及后续，感谢作者 MurphyWan。

其实之前也学习过Python的一些基本概念和操作，最近也时常有阅读廖雪峰的Python3教程，但这些基本概念的掌握和理解不是一朝一夕能够沉淀下来的，而我需要快速的能进入使用节奏。所以依靠这几篇博文学习练手。后续也需要继续深入学习Python概念与ipython。

**如果你想要按照此笔记学习，请下载本文件，然后用jupyter notebook或线上的一些jupyter notebook打开编辑，自己运行试试。**

## Python基础知识



### 常用数据类型


|名称|表示|声明示例|
|--|--|--|
|整数|int|a=10|
|浮点数|float|b=3.14|
|复数|complex|c=1+2j|
|字符串|str|d="python"|

### 算数运算符

|名称|表示|声明示例|
|--|--|--|
|加法|+|a+b|
|减法|-|c-b|
|乘法|*|x*y|
|除法|/|x/z|
|取模|%|x%a|
|取幂|**|a**x|

### 练习

In [1]:
a = 10 # int
a

10

In [2]:
b = 3.14 # float
b

3.14

In [3]:
d = a ** 2 # a的乘方
d

100

In [4]:
print(type(d)) # 返回d类型

<class 'int'>


In [5]:
print(type(d/10)) # 返回d/10类型

<class 'float'>


In [6]:
print(type(a/b)) # 返回a/b类型

<class 'float'>


In [7]:
c = 3 # int
print(type(a/c)) # 返回a/c类型

<class 'float'>


In [9]:
print(type(b*d)) # 返回bd类型

<class 'float'>


### 浮点数的精度

In [10]:
0.1 + 0.2

0.30000000000000004

这是二进制浮点的本质。
> 浮点数也就是小数，之所以称为浮点数，是因为按照科学记数法表示时，一个浮点数的小数点位置是可变的，比如，1.23x109和12.3x108是完全相等的。浮点数可以用数学写法，如1.23，3.14，-9.01，等等。但是对于很大或很小的浮点数，就必须用科学计数法表示，把10用e替代，1.23x109就是1.23e9，或者12.3e8，0.000012可以写成1.2e-5，等等。

>整数和浮点数在计算机内部存储的方式是不同的，整数运算永远是精确的（除法难道也是精确的？是的！），而浮点数运算则可能会有四舍五入的误差。

> --- 摘自廖雪峰Python3教程

可以使用`rond()`函数控制显示精度，但也有一些意外，比如`round(9.995, 2)`返回9.99而不是10，因为9.995在存储时是稍小于9.995的。

In [11]:
round(9.995, 2)

9.99

decimal Library可以给出精确的存储值，看下面的例子。

In [15]:
import decimal # import decimal library
# display 2 decimal precision
print(round( 3.1415, 2)) 
print(round(9.995, 2))

print(decimal.Decimal(9.995))

3.14
9.99
9.9949999999999992184029906638897955417633056640625


In [18]:
### 字符str的一些功能
t = "He is a string. Who are you?"
print(t.capitalize()) # 首字母大写
print(t.split()) # 分割字符
print(t.find('i')) # 查找字符i索引值
print(t.find('in'))
print(t.find('Python'))
print(t[0:4])
print(t.replace(' ', '|')) # 修改分隔符
w = 'http://www.google.com'
print(w.strip('http://')) # 删掉字符

He is a string. who are you?
['He', 'is', 'a', 'string.', 'Who', 'are', 'you?']
3
11
-1
He i
He|is|a|string.|Who|are|you?
www.google.com


**注意Python的索引从0开始，不包括最后的位置。比如[0:4]是取得前4个子项。**

### 基本的数据结构

|名称|表示|声明示例|
|--|--|--|
|元组|tuple|b=(1,2.5,'data')|
|列表|list|c=[1,2.5,'data']|
|字典|dict|d={'Name':'Kobe','Country':'US'}|
|集合|set|e=set(['u','d','ud','d','du'])|


    元组（tuple）只有几种方法可以更改。
    列表（list）比元组更灵活。
    字典（dict）是一个键值对存储对象。
    集合（set）是对象中唯一的无序集合对象。


### 列表的一些有用功能

In [19]:
l = [1, 2, 3.14, 'data'] # list
print( type(l))
l.append([4, 3]) # 添加列表
print(l)
l.insert(3, 'beta') # 在index 3前插入
print(l)
l.remove('data') # 删除
print(l)

<class 'list'>
[1, 2, 3.14, 'data', [4, 3]]
[1, 2, 3.14, 'beta', 'data', [4, 3]]
[1, 2, 3.14, 'beta', [4, 3]]


### 对象引用

In [20]:
x = [1, 2, 3, 4]
y = x
y[0] = 5
print(x)

x = [1, 2, 3, 4]
z = x.copy()
z[0] = 5
print(x)

[5, 2, 3, 4]
[1, 2, 3, 4]


**注意上述两者引用方式的差异性，如果只是简单地使用`=`进行赋值，只是给地址添加了一个字符对象引用，上述`y`与`x`是指向同一个地址，所以改动`y`也会改动`x`。**

### 多维列表

我们下面创建一个包含多行的列表。

In [21]:
a = [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3]]
print(a)
print(a[0][3])

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3]]
4


注意多维列表不是矩阵。

### 条件语句

控制元素包括if, else, elif

判断方式包括`>`,`<`,`==`,`>=`,`<=`

In [24]:
a = [24, 16, 54]
b = []

if a[0] < a[1] or a[0] < a[2]:
    b.append(a[0])
    if a[1] < a[2]:
        b.append(a[1])
        b.append(a[2])
    else:
        b.append(a[2])
        b.append(a[1])

print(b)

[24, 16, 54]


### 循环语句

循环语句有不同的代码样式，这里列出最常用的两种：

```python
# 1
for ... in ...: statement A
# 2
while ...: statement A
```

In [26]:
# 举例
for i in range(2, 10, 3):
    print(i)
    l = i ** 2
    print(l)
    
a = 0
sumup = 0
while a < 100:
    a += 1
    sumup += a
print(sumup)

2
4
5
25
8
64
5050


### break和continue

- 你可以在循环语句中使用break关键字跳出循环。
- 你可以在循环语句中使用continue关键字暂停当前的循环执行后面的语句。

In [27]:
# 举例
# 找第一个能被17整除的数
for i in range(300, 351):
    if i % 17 == 0:
        print(i)
        break
    else:
        continue

306


### 循环语句嵌套

就是循环中嵌套循环


```Python
for in range(10):
    print(i)
    for(j in range(5)):
        print(j)
```

### 练习

- 计算从1到1000的累积值
- 计算从1到1000的偶数之和

In [33]:
# 1
r = 1
for i in range(1,1001):
    r = r * i
print("累积值为",r)

# 2
s = 0
for i in range(1, 1001):
    if i % 2 == 0:
        s = s + i
print("偶数之和为",s)

累积值为 40238726007709377354370243392300398571937486421071463254379991042993851239862902059204420848696940480047998861019719605863166687299480855890132382966994459099742450408707375991882362772718873251977950595099527612087497546249704360141827809464649629105639388743788648733711918104582578364784997701247663288983595573543251318532395846307555740911426241747434934755342864657661166779739666882029120737914385371958824980812686783837455973174613608537953452422158659320192809087829730843139284440328123155861103697680135730421616874760967587134831202547858932076716913244842623613141250878020800026168315102734182797770478463586817016436502415369139828126481021309276124489635992870511496497541990934222156683257208082133318611681155361583654698404670897560290095053761647584772842188967964624494516076535340819890138544248798495995331910172335555660213945039973628075013783761530712776192684903435262520001588853514733161170210396817592151090778801939317811419454525722386554146106289218796022383897

### 函数声明

**函数定义**

```python
def The_Name_of_Function(para1, para2):
    ...
    return Outcome
```

**函数调用**

```python
The_Name_of_Function(para1, para2)
```

In [34]:
# 举例，求两个变量最大值的函数
def MaxOfTwo(x1, x2):
    if x1 >= x2:
        return x1
    else:
        return x2
    
a = 1
b = 2
c = MaxOfTwo(a, b)
print(c)

2


### 默认参数

我们可以为函数的参数提供默认值，例如：
```python
def MaxOfTwo(x1, x2 = 1):
    ...
 ```

### 返回多个输出

可以通过元组返回两个或多个输出：

```python
def  f (x1, x2,  x3, ...):
     ......
     return(y1,  y2,  y3, ...)

a1,b1,c1 = f(...)
```

### 读/写文件

#### 内建open()方法

要打开一个文件，使用Python内建的open()函数。 open()方法返回一个文件对象，最常用的一般使用两个参数。

```python
file_object = open(filename, mode)
```

这个mode参数可以是

    'r' 只读模式（when the file will only be read）
    'w' 只写模式（与一个现存文件文件同名，则被清除）
    'a' 添加模式，即任意写入文件的数据都被自动添加到末尾
    'r+' 打开文件，可以读、写



#### 创建文件


In [35]:
file = open('newfile.txt', 'w')
file.write('I am created for the course. \n')
file.write('How about you?\n')
file.write('How is your exam?')
file.close()

#### 读取一个文件

In [37]:
file = open('newfile.txt', 'r')
# 输出整个文件
print(file.read())
file.close()
# 输出前10个字符
file = open('newfile.txt', 'r')
print(file.read(10))
file.close()
# 输出一行
file = open('newfile.txt', 'r')
print(file.readline())
file.close()
# 输出多行
file = open('newfile.txt', 'r')
print(file.readlines())
file.close()

I am created for the course. 
How about you?
How is your exam?
I am creat
I am created for the course. 

['I am created for the course. \n', 'How about you?\n', 'How is your exam?']


#### 循环读取一个文件


In [38]:
file = open('newfile.txt', 'r')
for line in file:
    print(line)
file.close()

I am created for the course. 

How about you?

How is your exam?


In [39]:
# 上述输出的不是原文本，因为print的同时又加了一个'\n'
file = open('newfile.txt', 'r')
for line in file:
    print(line.strip())
file.close()

I am created for the course.
How about you?
How is your exam?


#### 添加文本

In [40]:
file = open('newfile.txt', 'a')
file.write('\nI am back again. \n')
file.write('Do you miss me? \n')
file.close()
# 查看
file = open('newfile.txt', 'r')
# 输出整个文件
print(file.read())
file.close()

I am created for the course. 
How about you?
How is your exam?
I am back again. 
Do you miss me? 



#### with语句

最好使用with()函数进行文本读写，它会自动关闭文件。

```python
with(open("humpty.txt") as f:
    ...
 ```

这样即使读取时发生错误，也可以确保文件正确关闭。

## 进阶

**用Numpy, Scipy, Matplotlib等模块进行计算，解决一些数学问题**

### 导入模块

通过import关键字导入模块

```python
import numpy
```

用as关键字给模块一个简称

```python
import numpy as np
```

有时候我们不必导入整个模块，只要导入部分功能函数

```python
from scipy.stats imports norm
```

### 练习

尝试导入时间模块，用它获取计算机运行指定代码所需要的时间


In [41]:
import timeit

def funl(x, y):
    return x**2 + y**3

t_start = timeit.default_timer()
z = funl(109.2, 367.1)
t_end = timeit.default_timer()

cost = t_end - t_start
print('Time cost of funl is %f' %cost)

Time cost of funl is 0.000094


我们会用到的模块有：

- NumPy: 多维数组操作，高效的数学计算函数
- Matplotlib: 可视化
- SciPy: 大型库实现各种数值算法，例如：
    - 线性和非线性方程解
    - 优化
    - 数值整合
- Sympy: 符号计算
- Pandas： 统计与数据分析

### Numpy

#### ndarray类型

NumPy提供了一种新的数据类型：ndarray（n维数组）。

    与元组和列表不同，数组只能存储相同类型的对象（例如只有floats或只有ints）
    这使得数组上的操作比列表快得多; 此外，数组占用的内存少于列表。
    数组为列表索引机制提供强大的扩展。


#### 创建ndarray

In [43]:
# 导入Numpy
import numpy as np
# 创建numpy数组
np.array([2,3,6,7])

array([2, 3, 6, 7])

In [44]:
np.array([2,3,6,7.])


array([ 2.,  3.,  6.,  7.])

In [45]:
np.array([2,3,6,7+1j])

array([ 2.+0.j,  3.+0.j,  6.+0.j,  7.+1.j])

#### 创建均匀间隔的数组

arrange:

In [47]:
np.arange(5)

array([0, 1, 2, 3, 4])

range(start, stop, step)的所有三个参数即起始值，结束值，步长都是可以用的 另外还有一个数据的dtype参数

In [48]:
np.arange(10, 100, 20, dtype = float)

array([ 10.,  30.,  50.,  70.,  90.])

linspace（start，stop，num）返回数字间隔均匀的样本，按区间[start，stop]计算：

In [49]:
np.linspace(0., 2.5, 5)

array([ 0.   ,  0.625,  1.25 ,  1.875,  2.5  ])

#### 多维数组矩阵

In [57]:
a = np.array([[1, 2, 3],[4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a.shape

(2, 3)

In [60]:
a.ndim

2

In [61]:
a.size

6

#### 形状变化

In [62]:
import numpy as np

a = np.arange(0, 20, 1) # 1维
b = a.reshape((4,5)) # 4行5列
c = a.reshape((20,1)) # 2维
d = a.reshape((-1, 4)) # -1：自动确定


In [63]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
c

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [66]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

**Size（N，），（N，1）和（1，N）是不同的!!!**


    Size（N, ）表示数组是一维的。
    Size（N，1）表示数组是维数为2, N列和1行。
    Size（1，N）表示数组是维数为2, 1行和N列。


In [68]:
# 例子
import numpy as np

a = np.array([1,2,3,4,5])
b = a.copy ()

c1 =  np.dot(np.transpose(a), b)
print(c1)
c2  = np.dot(a, np.transpose(b))
print(c2)

ax  =  np.reshape(a, (5,1))
bx  =  np.reshape(b, (1,5))
c = np.dot(ax, bx)
print(c)

55
55
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


#### 使用相同元素填充数组


In [69]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [70]:
np.zeros((2,2), complex)

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]])

In [71]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

#### 使用随机数字填充数组

rand: 0和1之间均匀分布的随机数

In [72]:
np.random.rand(2, 4)

array([[ 0.64006312,  0.52507683,  0.19150809,  0.14512848],
       [ 0.44435529,  0.54196468,  0.67622118,  0.28109175]])

#### randn: 均值为0，标准差为1的标准（高斯）正态分布

In [73]:
np.random.randn(2, 4)

array([[ 0.66849307,  0.52848045, -0.31279224,  1.53961143],
       [-1.2584165 ,  1.09309986, -0.16010106, -0.30071292]])

#### 一维数组切片


以格式start：stop可以用来提取数组的片段（从开始到不包括stop）

In [74]:
a = np.array([0, 1, 2, 3, 4])

In [75]:
a[1:3]

array([1, 2])

start可以省略，在这种情况下，它被设置为零(Notes:貌似留空更合适)：

In [76]:
a[:3]

array([0, 1, 2])

stop也可以省略，在这种情况下它被设置为数组长度：

In [77]:
a[1:]

array([1, 2, 3, 4])

也可以使用负指数，具有标准含义：

In [78]:
a[1:-1]

array([1, 2, 3])

整个数组：a或a [：]

In [80]:
a

array([0, 1, 2, 3, 4])

In [81]:
a[:]

array([0, 1, 2, 3, 4])

按步长获取元素

In [82]:
a[::2]

array([0, 2, 4])

-1的这个步骤可用于反转数组：

In [83]:
a[::-1]

array([4, 3, 2, 1, 0])

#### 二维数组切片


对于多维数组，索引是整数元组

In [84]:
a = np.arange(12)
a.shape = (3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a[1, 2]

6

In [86]:
a[1, -1]

7

索引的工作与列表完全相同

In [88]:
a[:, 1] # 这是第二列

array([1, 5, 9])

In [89]:
a[2, :]

array([ 8,  9, 10, 11])

In [90]:
a[1][2]

6

不必明确提供尾随的冒号

In [91]:
a[2] # 按行

array([ 8,  9, 10, 11])

复杂点的索引

![](http://mmbiz.qpic.cn/mmbiz/nliazs07woqkq6aoUyEKB0WlJqwfFpSzZj4SpbZHGPibQcTv8YSMMbOWia0jWwqibGRJwMBricVIRlDZ6vlVqCLryGQ/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1)

### 副本（copy）和视图（view）


    采用标准的list切片为其建立副本
    采用一个NumPy数组的切片可以在原始数组中创建一个视图。 两个数组都指向相同的内存。因此，当修改视图时，原始数组也被修改：


In [94]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [95]:
b = a[2:]
b

array([2, 3, 4])

In [96]:
b[0] = 100
b

array([100,   3,   4])

In [98]:
a # 对应位置变了

array([  0,   1, 100,   3,   4])

为避免修改原始数组，可以制作一个切片的副本

In [99]:
a = np.arange(5); a

array([0, 1, 2, 3, 4])

In [100]:
b = a[2:].copy(); b

array([2, 3, 4])

In [101]:
b[0] = 100
b

array([100,   3,   4])

In [102]:
a

array([0, 1, 2, 3, 4])

### 矩阵乘法


运算符 * 表示元素乘法，而不是矩阵乘法

In [104]:
A = np.array([[1, 2],[3, 4]])
A * A

array([[ 1,  4],
       [ 9, 16]])

使用dot（）函数进行矩阵乘法:

In [105]:
np.dot(A, A)

array([[ 7, 10],
       [15, 22]])

dot（）方法也适用于矩阵向量(matrix-vector)乘法：

In [106]:
x = np.array([10, 20])
np.dot(A, x)

array([ 50, 110])

In [107]:
np.dot(x, A)

array([ 70, 100])

### 将数组保存到文件

savetxt()将表保存到文本文件。

这里我就照着拷贝下啦，不存了

```python
In  [1]: a = np.linspace(0. 1, 12); a.shape(3, 4); a
Out [1] :
array([[ 0.  ,  0.09090909, 0.18181818,  0.27272727],
[  0.36363636,  0.45454545, 0.54545455,  0.63636364],
[  0.72727273,  0.81818182. 0.90909091,  1.]])

In [2] : np.savetxt("myfile.txt", a)
```

save()将表保存为Numpy“.npy”格式的二进制文件

```python
In [3] : np.save("myfile" ,a)   
```

### 将文本文件读入数组

loadtxt（）将以文本文件存储的表读入数组。

```python
   In [1] : tabla = np.loadtxt("data.txt")
   In [2] : table
   Out[2] :
   array ([[ 1.99000000e+03,   -1.50000000e+00,   2.53000000e+01],    
   [ 1.9910000e+03,  -3.2000000e+00,  2.12000000e+01]

```

默认情况下，loadtxt()假定列是用空格分隔的。 您可以通过修改可选的参数.Lines进行更改。 以（＃）开头的行将被忽略。

#### Numpy包含更高效率的功能



    Numpy包含许多常用的数学函数，例如：
        np.log
        np.maximum
        np.sin
        np.exp
        np.abs

    在大多数情况下，Numpy函数比Math包中的类似函数更有效，特别是对于大规模数据。
